---
swagger: "2.0"
info:
  description: "CapableHealthService"
  version: "2022-12-22T15:14:09Z"
  title: "CapableHealthService"
host: "gandsaqbh7.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /capablehealthservice:
    post:
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CapableHealth"
        required: true
        schema:
          $ref: "#/definitions/CapableHealth"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  CapableHealth:
    type: "object"
    required:
    - "action"
    - "appointmentTypeID"
    - "calendarID"
    - "id"
    properties:
      id:
        type: "integer"
        format: "int64"
      action:
        type: "string"
        format: "byte"
      calendarID:
        type: "string"
        format: "byte"
      appointmentTypeID:
        type: "string"
        format: "byte"
